services:
  bot:
    build: .
    env_file: .env
    environment: 
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on: 
      - db
    volumes:
      - ./src/pyWeastCoastBot/db/migrations:/app/src/pyWeastCoastBot/db/migrations
    command: ["./bin/wait-for-it.sh", "db:5432", "--", "./bin/start.sh"]
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /app
  db:
    image: postgres:13.4
    volumes:
      - postgres:/var/lib/postgresql/data
    expose: 
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
