services:
  bot:
    # Mount migrations so they are persisted to host
    volumes:
      - ./src/pyWeastCoastBot/db/migrations:/app/src/pyWeastCoastBot/db/migrations
    develop:
      watch:
        - path: src
          action: sync+restart
          target: /app/src
