"""server scoping

Revision ID: 2077cfc26e01
Revises: f75546b2dd35
Create Date: 2025-11-21 12:41:28.482723

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2077cfc26e01"
down_revision: Union[str, Sequence[str], None] = "f75546b2dd35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reminder", sa.Column("guild_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reminder", "guild_id")
    # ### end Alembic commands ###
