# Generated by Django 3.2.7 on 2021-09-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
