# Generated by Django 3.2.7 on 2021-10-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_reminder_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('provider', models.TextField()),
                ('guild_id', models.TextField()),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('scope', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'provider', 'guild_id')},
            },
        ),
    ]
